In [36]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [37]:
data = pd.read_csv("classData.csv")

In [38]:
data.tail()

,G,C,B,A,Ia,Ib,Ic,Va,Vb,Vc
7856,0,0,0,0,-66.237921,38.457041,24.912239,0.094421,-0.552019,0.457598
7857,0,0,0,0,-65.849493,37.465454,25.515675,0.103778,-0.555186,0.451407
7858,0,0,0,0,-65.446698,36.472055,26.106554,0.113107,-0.558211,0.445104
7859,0,0,0,0,-65.029633,35.477088,26.684731,0.122404,-0.561094,0.438690
7860,0,0,0,0,-64.598401,34.480799,27.250065,0.131669,-0.563835,0.432166

In [42]:
X = data.drop(['G', 'C' , 'B', 'A'], axis = 1)
Y = data[['G', 'C' , 'B', 'A']]

In [43]:
X.head()

           Ia          Ib          Ic        Va        Vb        Vc
0 -151.291812   -9.677452   85.800162  0.400750 -0.132935 -0.267815
1 -336.186183  -76.283262   18.328897  0.312732 -0.123633 -0.189099
2 -502.891583 -174.648023  -80.924663  0.265728 -0.114301 -0.151428
3 -593.941905 -217.703359 -124.891924  0.235511 -0.104940 -0.130570
4 -643.663617 -224.159427 -132.282815  0.209537 -0.095554 -0.113983

In [44]:
Y.head()

   G  C  B  A
0  1  0  0  1
1  1  0  0  1
2  1  0  0  1
3  1  0  0  1
4  1  0  0  1

In [45]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [46]:
X_train

              Ia          Ib          Ic        Va        Vb        Vc
6065   45.579072   36.385844  -85.372305 -0.203901  0.614326 -0.410424
280   681.901631   10.650962   32.835516  0.192738 -0.521142  0.328404
4958  700.107216 -817.132747  117.023269 -0.007347 -0.032424  0.039771
3019    5.289049  594.071848 -596.761528  0.430847  0.025237 -0.456085
5849  -70.153443   51.710424   14.972373  0.025748 -0.522188  0.496439
...          ...         ...         ...       ...       ...       ...
1776  860.082066 -325.904635   22.222759  0.025395 -0.327965  0.302570
6560  -36.480549   97.394464  -64.163046 -0.602329  0.189966  0.412364
2071   71.336432 -799.993824  -54.917567 -0.035787  0.210146 -0.174359
1113  317.595505  -25.424114   47.157174  0.331243 -0.605829  0.274586
6215  -70.338667   79.684058  -12.704054 -0.287124 -0.311158  0.598283

[6288 rows x 6 columns]

In [63]:
rfc = RandomForestClassifier(n_estimators = 30)
rfc.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=30)

In [64]:
Y_pred = rfc.predict(X_test)

In [65]:
accuracy_score(Y_test, Y_pred )

0.8734901462174189

In [67]:
cols = data.columns.drop(['G', 'C' , 'B', 'A'])
feature_importance = pd.Series(rfc.feature_importances_, index = cols)
feature_importance

Ia    0.259343
Ib    0.164358
Ic    0.240077
Va    0.111178
Vb    0.110760
Vc    0.114284
dtype: float64