In [25]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [3]:
data = pd.read_csv("detect_dataset.csv")

In [5]:
data.head()

,Output (S),Ia,Ib,Ic,Va,Vb,Vc,Unnamed: 7,Unnamed: 8
0,0,-170.472196,9.219613,161.252583,0.054490,-0.659921,0.605431,NaN,NaN
1,0,-122.235754,6.168667,116.067087,0.102000,-0.628612,0.526202,NaN,NaN
2,0,-90.161474,3.813632,86.347841,0.141026,-0.605277,0.464251,NaN,NaN
3,0,-79.904916,2.398803,77.506112,0.156272,-0.602235,0.445963,NaN,NaN
4,0,-63.885255,0.590667,63.294587,0.180451,-0.591501,0.411050,NaN,NaN

In [9]:
data1 = data.drop("Unnamed: 7", axis =1)

In [10]:
data1.head()

,Output (S),Ia,Ib,Ic,Va,Vb,Vc,Unnamed: 8
0,0,-170.472196,9.219613,161.252583,0.054490,-0.659921,0.605431,NaN
1,0,-122.235754,6.168667,116.067087,0.102000,-0.628612,0.526202,NaN
2,0,-90.161474,3.813632,86.347841,0.141026,-0.605277,0.464251,NaN
3,0,-79.904916,2.398803,77.506112,0.156272,-0.602235,0.445963,NaN
4,0,-63.885255,0.590667,63.294587,0.180451,-0.591501,0.411050,NaN

In [11]:
data2 = data1.drop("Unnamed: 8", axis =1)

In [12]:
data2.head()

   Output (S)          Ia        Ib          Ic        Va        Vb        Vc
0           0 -170.472196  9.219613  161.252583  0.054490 -0.659921  0.605431
1           0 -122.235754  6.168667  116.067087  0.102000 -0.628612  0.526202
2           0  -90.161474  3.813632   86.347841  0.141026 -0.605277  0.464251
3           0  -79.904916  2.398803   77.506112  0.156272 -0.602235  0.445963
4           0  -63.885255  0.590667   63.294587  0.180451 -0.591501  0.411050

In [14]:
X = data2.drop("Output (S)", axis =1 )
Y = data2["Output (S)"]

In [15]:
X

               Ia         Ib          Ic        Va        Vb        Vc
0     -170.472196   9.219613  161.252583  0.054490 -0.659921  0.605431
1     -122.235754   6.168667  116.067087  0.102000 -0.628612  0.526202
2      -90.161474   3.813632   86.347841  0.141026 -0.605277  0.464251
3      -79.904916   2.398803   77.506112  0.156272 -0.602235  0.445963
4      -63.885255   0.590667   63.294587  0.180451 -0.591501  0.411050
...           ...        ...         ...       ...       ...       ...
11996  -66.237921  38.457041   24.912239  0.094421 -0.552019  0.457598
11997  -65.849493  37.465454   25.515675  0.103778 -0.555186  0.451407
11998  -65.446698  36.472055   26.106554  0.113107 -0.558211  0.445104
11999  -65.029633  35.477088   26.684731  0.122404 -0.561094  0.438690
12000  -64.598401  34.480799   27.250065  0.131669 -0.563835  0.432166

[12001 rows x 6 columns]

In [16]:
Y

0        0
1        0
2        0
3        0
4        0
        ..
11996    0
11997    0
11998    0
11999    0
12000    0
Name: Output (S), Length: 12001, dtype: int64

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [18]:
X_train

               Ia          Ib          Ic        Va        Vb        Vc
11554  -69.112530   76.553696  -10.434284 -0.294045 -0.305425  0.599470
6549  -780.301883  164.468106  618.015302 -0.053909  0.043773  0.010136
11043   18.711224   69.164651  -91.019650 -0.493506  0.579611 -0.086105
5442    21.685940 -774.469288  755.155732 -0.196043  0.000276  0.195767
7345  -879.897972  378.082746  503.836095 -0.022682  0.042349 -0.019667
...           ...         ...         ...       ...       ...       ...
1455   197.295451   58.162470  -48.224836 -0.381752  0.506856 -0.125104
8387   -67.174035   45.015014   23.986323  0.010633 -0.519636  0.509002
4967    56.560467 -344.386294  290.490050  0.354018  0.039245 -0.393263
7676    11.621323  -40.920444   31.259987  0.597231 -0.359733 -0.237498
3607   439.387604   -4.907384   34.920276  0.285947 -0.579463  0.293517

[9600 rows x 6 columns]

In [19]:
Y_train

11554    0
6549     1
11043    0
5442     1
7345     1
        ..
1455     1
8387     0
4967     1
7676     0
3607     1
Name: Output (S), Length: 9600, dtype: int64

In [20]:
rfc = RandomForestClassifier(n_estimators = 20)
rfc.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=20)

In [22]:
Y_pred = rfc.predict(X_test)

In [23]:
Y_pred

array([1, 0, 0, ..., 0, 0, 0], shape=(2401,))

In [26]:
accuracy_score(Y_test, Y_pred )

0.9966680549770929

In [35]:
cols = data2.columns.drop("Output (S)")
feature_importance = pd.Series(rfc.feature_importances_, index = cols)
feature_importance

Ia    0.349915
Ib    0.346877
Ic    0.077413
Va    0.082125
Vb    0.079376
Vc    0.064295
dtype: float64